### ISSUE TITLE
configurable layout

### ISSUE THREAD

**Issue by bkhouri** [bluz71/bash-seafly-prompt#1]
It's great that this provides some bash prompt configuration, however, it would be nice to allow to configure the layout.

the default layout is `<Host> <Git Branch> <Git Indicators> <Current Path> <Prompt Symbol>` But I like to use the following layout
`<user>@<host> <current path> <git branch> <prompt symbol>`

I know I can modify the file directly, but then we wouldn't be able to do 'git pull' to retrieve the fixes.

**Comment by bluz71** [comment]
Good suggestions.

Latest update should satisfy.

You need to set the following variables:

```sh
SEAFLY_SHOW_USER=1
SEAFLY_LAYOUT=2
```

If you don't want any Git indicators then also do:

```sh
GIT_PS1_SHOWDIRTYSTATE=0
GIT_PS1_SHOWSTASHSTATE=0
GIT_PS1_SHOWUPSTREAM=0
```

**Comment by bkhouri** [comment]
Thanks for the quick fix!
